# Generated by Django 4.1.4 on 2022-12-27 04:12

import apps.user.validations
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=apps.user.validations.generate_path_upload_images, validators=[apps.user.validations.validate_image_size, apps.user.validations.validate_image_format]),
        ),
    ]
