# Generated by Django 4.1.4 on 2022-12-27 04:45

import apps.user.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=apps.user.validations.generate_path_upload_images, validators=[apps.user.validations.validate_image_size, apps.user.validations.validate_image_format]),
        ),
    ]
