# Generated by Django 4.1.4 on 2023-03-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type_user',
            field=models.CharField(choices=[('A', 'Adoptante'), ('O', 'Organización')], max_length=1),
        ),
    ]
