# Generated by Django 4.1.4 on 2022-12-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_adoptionform_pet_status_alter_petimage_pet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionform',
            name='second_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
