# Generated by Django 4.1.4 on 2023-01-20 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_alter_adoptionform_second_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adoptionform',
            options={'verbose_name': 'Formulario de adopción', 'verbose_name_plural': 'Formularios de adopción'},
        ),
        migrations.AlterModelOptions(
            name='adoptionrequest',
            options={'verbose_name': 'Solicitud de adopción', 'verbose_name_plural': 'Solcitudes de adopción'},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name': 'Mascota', 'verbose_name_plural': 'Mascotas'},
        ),
        migrations.AlterModelOptions(
            name='petimage',
            options={'verbose_name': 'Imagen', 'verbose_name_plural': 'Imagenes'},
        ),
    ]
