# Generated by Django 4.1.4 on 2023-03-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_alter_adoptionform_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionrequest',
            name='status',
            field=models.CharField(choices=[('S', 'Enviado'), ('A', 'Aprobado'), ('R', 'Rechazado')], max_length=1),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Hembra')], max_length=1),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Pequeño'), ('S', 'Pequeño'), ('M', 'Mediano'), ('L', 'Grande'), ('XL', 'Extra Grande')], max_length=2),
        ),
        migrations.AlterField(
            model_name='pet',
            name='type_of_pet',
            field=models.CharField(choices=[('D', 'Perro'), ('C', 'Gato')], max_length=1),
        ),
    ]
